spring:
  application:
    name: deepfine-inventory
  datasource:
    url: "${DB_URL:jdbc:postgresql://localhost:5432/deepfine_inventory}"
    username: "${DB_USERNAME:deepfine}"
    password: "${DB_PASSWORD:deepfine}"
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
